# Generated by Django 3.1.5 on 2021-01-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0, max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='upload/product')),
            ],
        ),
    ]
